# -*- coding: utf-8 -*-
"""rapor8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hk5C7L5zCAqtCQfAr1rB0Vt9LrHLnNWo
"""

!pip install biopython

!wget https://www.drive5.com/muscle/downloads3.8.31/muscle3.8.31_i86linux64.tar.gz

!ls

!pwd

!tar -xvzf muscle3.8.31_i86linux64.tar.gz

!/content/muscle3.8.31_i86linux64 -in seqs.fa -out seqs.afa

!./muscle3.8.31_i86linux64

!./muscle3.8.31_i86linux64 -in seqs.fa -out seqs.afa

!./muscle3.8.31_i86linux64 -in seqs.fa -out seqs.afa -maxiters 2

!./muscle3.8.31_i86linux64 -in seqs.fa -out seqs.afa -maxiters 1 -diags -sv -distance1 kbit20_3

!./muscle3.8.31_i86linux64 -in seqs.fa -out seqs.afa -maxiters 1 -diags

!./muscle3.8.31_i86linux64 -in seqs.fa -out seqs.afa -maxiters 1 -diags1 -sv

"""2.7 Pipelining"""

!./muscle3.8.31_i86linux64 < seqs.fa > seqs.afa

"""2.8 Refining an existing alignment"""

!./muscle3.8.31_i86linux64 -in seqs.afa -out refined.afa -refine

"""2.9 Using a pre-computed guide tree"""

!./muscle3.8.31_i86linux64 -in seqs.fa -out seqs.afa -usetree /content/mytree.phy

"""WARNİNG"""

!./muscle3.8.31_i86linux64 -in seqs.fa -out seqs.afa -usetree_nowarn /content/mytree.phy

"""2.10 Profile-profile alignment;"""

!./muscle3.8.31_i86linux64 -profile -in1 one.afa -in2 two.afa -out both.afa

"""2.11 Adding sequences to an existing alignment"""

!./muscle3.8.31_i86linux64 -profile -in1 existing_aln.afa -in2 new_seq.fa -out combined.afa

!./muscle3.8.31_i86linux64 -in new_seqs.fa -out new_seqs.afa

!./muscle3.8.31_i86linux64 -profile -in1 existing_aln.afa -in2 new_seqs.fa -out combined.afas

"""2.12 Sequence clustering"""

!./muscle3.8.31_i86linux64 -cluster -in seqs.fa -tree1 tree.phy -maxiters 1

"""2.13 Specifying a substitution matrix"""

!./muscle3.8.31_i86linux64 -in seqs.fa -out seqs.afa -matrix blosum62 -gapopen -12.0

    -gapextend -1.0 -center 0.0

"""2.14 Refining a long alignment"""

!./muscle3.8.31_i86linux64 -in input.afa -out output.afa